### ISSUE TITLE
default gateway route?

### ISSUE THREAD

**Issue by cybacolt** [saltstack-formulas/network-debian-formula#1]
default gateway can be set by putting it in the /etc/network/route file:
`route add default gw <my gw> eth0`

wouldnt best practice put this as the 'gateway' option in the interfaces template?

**Comment by Sjd-Risca** [comment]
You can already do as you wish.

If you would check the pillar.example you can notice that you can set up the route in /etc/network/route file as you just said, or you can put it in the interfaces like the following example (see the last line):

``` yaml
  network:
    interfaces:
      - name: br0
        enabled: True
        comment: Bridge for use with KVM.
        proto: inet
        type: static
        address: 172.25.100.50
        netmask: 24
        options:
          - bridge_ports eth0
          - gateway 172.25.100.1
```

If this is satisfying I would close the bug report.
